name: horse_auction_app
description: Horse auction demo
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # FlutterFire (don’t use `firebase_functions`; use `cloud_functions`)
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  flutter_gen: ^5.12.0
  go_router: ^16.2.2

flutter:
  uses-material-design: true
  generate: true
