name: horse_auction_app
description: Horse auction demo
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.8
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter

# (optional) Arabic font that looks nice
fonts:
  - family: NotoNaskhArabic
    fonts:
      - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
      - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
        weight: 700

flutter:
  uses-material-design: true
  generate: true