name: horse_auction_app
description: Horse auction demo
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
# (optional) Arabic font that looks nice
fonts:
  - family: NotoNaskhArabic
    fonts:
      - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
      - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
        weight: 700

flutter:
  uses-material-design: true
  generate: true
assets:
    - assets/horses/