// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE-0vVqBa2ERUJGeWYSp8tRVfbfp5HxTs',
    appId: '1:578694441278:web:2fc001437f397fa6bde46f',
    messagingSenderId: '578694441278',
    projectId: 'horse-auction-dev1',
    authDomain: 'horse-auction-dev1.firebaseapp.com',
    storageBucket: 'horse-auction-dev1.firebasestorage.app',
    measurementId: 'G-YKHYJVQPK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHnDJVhMB6syz15iay_SxiZynwH3r1wd0',
    appId: '1:578694441278:android:f11aaf8d365e9a3abde46f',
    messagingSenderId: '578694441278',
    projectId: 'horse-auction-dev1',
    storageBucket: 'horse-auction-dev1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjJNypC0ag-PMaQ3ae9Atvu8LdoHAi8GQ',
    appId: '1:578694441278:ios:141ff2fb4bc490a6bde46f',
    messagingSenderId: '578694441278',
    projectId: 'horse-auction-dev1',
    storageBucket: 'horse-auction-dev1.firebasestorage.app',
    iosBundleId: 'com.example.horseAuction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE-0vVqBa2ERUJGeWYSp8tRVfbfp5HxTs',
    appId: '1:578694441278:web:8756e94c811bfc86bde46f',
    messagingSenderId: '578694441278',
    projectId: 'horse-auction-dev1',
    authDomain: 'horse-auction-dev1.firebaseapp.com',
    storageBucket: 'horse-auction-dev1.firebasestorage.app',
    measurementId: 'G-N8H1VH9Q41',
  );

}