// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjLI8jKB3q1uTQBTe_7mYHSSbqjcIcbo',
    appId: '1:1006357064889:web:63125d205a2d8d70cabf68',
    messagingSenderId: '1006357064889',
    projectId: 'horse-auction-saudi',
    authDomain: 'horse-auction-saudi.firebaseapp.com',
    storageBucket: 'horse-auction-saudi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKjLI8jKB3q1uTQBTe_7mYHSSbqjcIcbo',
    appId: '1:1006357064889:web:b251f9a722beab3ccabf68',
    messagingSenderId: '1006357064889',
    projectId: 'horse-auction-saudi',
    authDomain: 'horse-auction-saudi.firebaseapp.com',
    storageBucket: 'horse-auction-saudi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDw8BBO3Sno6yXxViQP_X4Tw3tEfkX1cg',
    appId: '1:1006357064889:ios:314b04c3f88532eecabf68',
    messagingSenderId: '1006357064889',
    projectId: 'horse-auction-saudi',
    storageBucket: 'horse-auction-saudi.firebasestorage.app',
    iosBundleId: 'com.example.horseAuctionApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuILnW-gJJ3Ora_mIknGoZAE-5g27zCnw',
    appId: '1:1006357064889:android:125bd03368bd6146cabf68',
    messagingSenderId: '1006357064889',
    projectId: 'horse-auction-saudi',
    storageBucket: 'horse-auction-saudi.firebasestorage.app',
  );

}