import 'package:horse_auction_baseline/models/lot_model.dart';

final List<Lot> seedLots = [
  Lot(
    id: 'L1',
    name: 'Desert Comet',
    description: 'Fast bay gelding with great temperament.',
    coverImage: 'https://picsum.photos/seed/horse1/800/500',
    startingPrice: 2500.0,
    currentBid: 2500.0,
    minIncrement: 100.0,
    endsAt: DateTime.now().add(const Duration(minutes: 5)),
  ),
  Lot(
    id: 'L2',
    name: 'Silver Mirage',
    description: 'Elegant mare, excellent conformation.',
    coverImage: 'https://picsum.photos/seed/horse2/800/500',
    startingPrice: 3000.0,
    currentBid: 3000.0,
    minIncrement: 150.0,
    endsAt: DateTime.now().add(const Duration(minutes: 7)),
  ),
  Lot(
    id: 'L3',
    name: 'Storm Strider',
    description: 'Athletic stallion with powerful stride.',
    coverImage: 'https://picsum.photos/seed/horse3/800/500',
    startingPrice: 1800.0,
    currentBid: 1800.0,
    minIncrement: 75.0,
    endsAt: DateTime.now().add(const Duration(minutes: 3)),
  ),
  Lot(
    id: 'L4',
    name: 'Autumn Whisper',
    description: 'Calm mare, great for beginners.',
    coverImage: 'https://picsum.photos/seed/horse4/800/500',
    startingPrice: 2200.0,
    currentBid: 2200.0,
    minIncrement: 100.0,
    endsAt: DateTime.now().add(const Duration(minutes: 9)),
  ),
  Lot(
    id: 'L5',
    name: 'Midnight Arrow',
    description: 'Dark coat, strong endurance.',
    coverImage: 'https://picsum.photos/seed/horse5/800/500',
    startingPrice: 2700.0,
    currentBid: 2700.0,
    minIncrement: 125.0,
    endsAt: DateTime.now().add(const Duration(minutes: 12)),
  ),
  Lot(
    id: 'L6',
    name: 'Golden Dancer',
    description: 'Palomino with smooth gaits.',
    coverImage: 'https://picsum.photos/seed/horse6/800/500',
    startingPrice: 3200.0,
    currentBid: 3200.0,
    minIncrement: 150.0,
    endsAt: DateTime.now().add(const Duration(minutes: 15)),
  ),
];
